name: Go

on: push

jobs:

  build:
    env:
      POSTGRESQL_URL: 'postgres://postgres:postgres@localhost:5432/es_go_local?sslmode=disable'
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Run migrations
      run: migrate -database $POSTGRESQL_URL -path db/migrations up  

    - name: Test
      run: go test -v ./...
