name: Go Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.3

      - uses: actions/checkout@v3

      - name: Lint and Vet
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
