name: Go Lint

on: push

jobs:
  lint:
    env:
      GOLANGCI_LINT_VERSION: 'v1.46.2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint and Vet
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=3m
