name: Go Test

on: push

jobs:
  test:
    env:
      POSTGRESQL_URL: 'postgres://postgres:postgres@localhost:5432/es_go_local?sslmode=disable'
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: es_go_local
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
    - id: go-cache-paths
      run: |
        echo "::set-output name=go-build::$(go env GOCACHE)"
        echo "::set-output name=go-mod::$(go env GOMODCACHE)"

    - uses: actions/checkout@v3

    # Cache go build cache, used to speedup go test
    - name: Go Build Cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.go-cache-paths.outputs.go-build }}
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

    # Cache go mod cache, used to speedup builds
    - name: Go Mod Cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.go-cache-paths.outputs.go-mod }}
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.1

    - name: Build
      run: go build -v ./...

    - name: Install golang-migrate
      env:
        GOLANG_MIGRATE_VERSION: 'v4.15.2'
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/$GOLANG_MIGRATE_VERSION/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/
        which migrate

    - name: Run migrations
      run:
        migrate -database $POSTGRESQL_URL -path db/migrations up

    - name: Run coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
